/*
 * This file is generated by jOOQ.
*/
package fr.caddarik.theblog.dao.jooq;


import fr.caddarik.theblog.dao.jooq.tables.PostTable;
import fr.caddarik.theblog.dao.jooq.tables.UserTable;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DefaultSchema extends SchemaImpl {

    private static final long serialVersionUID = -1944679804;

    /**
     * The reference instance of <code></code>
     */
    public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

    /**
     * The table <code>post</code>.
     */
    public final PostTable POST = fr.caddarik.theblog.dao.jooq.tables.PostTable.POST;

    /**
     * The table <code>user</code>.
     */
    public final UserTable USER = fr.caddarik.theblog.dao.jooq.tables.UserTable.USER;

    /**
     * No further instances allowed
     */
    private DefaultSchema() {
        super("", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(PostTable.POST,
            UserTable.USER);
    }
}
