/*
 * This file is generated by jOOQ.
*/
package fr.caddarik.theblog.dao.jooq;


import fr.caddarik.theblog.dao.jooq.tables.PostTable;
import fr.caddarik.theblog.dao.jooq.tables.UserTable;
import fr.caddarik.theblog.dao.jooq.tables.records.PostRecord;
import fr.caddarik.theblog.dao.jooq.tables.records.UserRecord;

import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code></code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<PostRecord> PK_POST = UniqueKeys0.PK_POST;
    public static final UniqueKey<UserRecord> PK_USER = UniqueKeys0.PK_USER;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<PostRecord, UserRecord> FK_POST_USER_1 = ForeignKeys0.FK_POST_USER_1;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<PostRecord> PK_POST = createUniqueKey(PostTable.POST, "pk_post", PostTable.POST.ID);
        public static final UniqueKey<UserRecord> PK_USER = createUniqueKey(UserTable.USER, "pk_user", UserTable.USER.ID);
    }

    private static class ForeignKeys0 extends AbstractKeys {
        public static final ForeignKey<PostRecord, UserRecord> FK_POST_USER_1 = createForeignKey(fr.caddarik.theblog.dao.jooq.Keys.PK_USER, PostTable.POST, "fk_post_user_1", PostTable.POST.USER_ID);
    }
}
