/*
 * This file is generated by jOOQ.
*/
package fr.caddarik.theblog.dao.jooq;


import fr.caddarik.theblog.dao.jooq.tables.PostTable;
import fr.caddarik.theblog.dao.jooq.tables.UserTable;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in 
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>post</code>.
     */
    public static final PostTable POST = fr.caddarik.theblog.dao.jooq.tables.PostTable.POST;

    /**
     * The table <code>user</code>.
     */
    public static final UserTable USER = fr.caddarik.theblog.dao.jooq.tables.UserTable.USER;
}
